# Generated by Django 5.0.5 on 2024-05-19 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0003_rename_owner_employer'),
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='employer',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='agency.employer'),
        ),
    ]
