# Generated by Django 5.1.1 on 2024-09-16 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_companyinfo_certificate_companyinfo_history_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyinfo',
            name='certificate',
            field=models.ImageField(blank=True, null=True, upload_to='certificates/'),
        ),
    ]
