# Generated by Django 5.1.1 on 2024-09-19 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_dictionary_expanded_answer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='certificate_text',
            field=models.CharField(default='For the best China company of 1989', max_length=50),
            preserve_default=False,
        ),
    ]
