# Generated by Django 5.1.1 on 2024-09-25 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0009_sponsor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsor',
            name='logo',
            field=models.CharField(max_length=255),
        ),
    ]
