# Generated by Django 5.1.1 on 2024-09-25 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0011_certificate_alter_companyinfo_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyinfo',
            name='certificate',
        ),
    ]
