# Generated by Django 5.1.1 on 2024-09-25 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0012_remove_companyinfo_certificate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Certificate',
        ),
        migrations.AlterModelOptions(
            name='companyinfo',
            options={'verbose_name': 'company info', 'verbose_name_plural': 'company info'},
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='certificate',
            field=models.ImageField(blank=True, null=True, upload_to='certificates/'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='certificate_text',
            field=models.CharField(default='Cool comp', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='history',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='information',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/'),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='requisites',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
