# Generated by Django 5.1.1 on 2024-09-30 18:32

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0013_delete_certificate_alter_companyinfo_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('subtitle', models.CharField(blank=True, max_length=255, null=True, verbose_name='Subtitle')),
                ('company_name', models.CharField(max_length=255, verbose_name='Company Name')),
                ('date_issued', models.DateField(default=django.utils.timezone.now, verbose_name='Date Issued')),
                ('registry_number', models.CharField(max_length=50, verbose_name='Registry Number')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='certificates/', verbose_name='Logo')),
                ('certificate_footer', models.TextField(blank=True, null=True, verbose_name='Footer Text')),
                ('certificate_image', models.ImageField(blank=True, null=True, upload_to='certificates/images/', verbose_name='Certificate Image')),
            ],
            options={
                'verbose_name': 'Certificate',
                'verbose_name_plural': 'Certificates',
            },
        ),
        migrations.AlterModelOptions(
            name='companyinfo',
            options={'verbose_name': 'Company Info', 'verbose_name_plural': 'Company Info'},
        ),
        migrations.RemoveField(
            model_name='companyinfo',
            name='certificate_text',
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='history',
            field=models.TextField(blank=True, null=True, verbose_name='History'),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='information',
            field=models.TextField(verbose_name='Information'),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/', verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='requisites',
            field=models.TextField(blank=True, null=True, verbose_name='Requisites'),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='video_url',
            field=models.URLField(blank=True, null=True, verbose_name='Video URL'),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='certificate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.certificate', verbose_name='Certificate'),
        ),
    ]
