# Generated by Django 5.1.1 on 2024-09-30 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0014_certificate_alter_companyinfo_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='signature_image',
            field=models.ImageField(blank=True, null=True, upload_to='certificates/signatures/', verbose_name='Signature Image'),
        ),
    ]
