# Generated by Django 5.0.5 on 2024-05-19 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PropertyType',
            new_name='Category',
        ),
    ]
