# Generated by Django 5.0.5 on 2024-05-19 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0002_rename_propertytype_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Owner',
            new_name='Employer',
        ),
    ]
