# Generated by Django 5.0.5 on 2024-05-19 20:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0003_rename_owner_employer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyer',
            name='phone_number',
            field=models.CharField(blank=True, max_length=255, validators=[django.core.validators.RegexValidator('\\+375 \\((29|33|25)\\) \\d{3}-\\d{2}-\\d{2}'), django.core.validators.MinLengthValidator(19), django.core.validators.MaxLengthValidator(19)]),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone_number',
            field=models.CharField(blank=True, max_length=255, validators=[django.core.validators.RegexValidator('\\+375 \\((29|33|25)\\) \\d{3}-\\d{2}-\\d{2}'), django.core.validators.MinLengthValidator(19), django.core.validators.MaxLengthValidator(19)]),
        ),
        migrations.AlterField(
            model_name='employer',
            name='phone_number',
            field=models.CharField(blank=True, max_length=255, validators=[django.core.validators.RegexValidator('\\+375 \\((29|33|25)\\) \\d{3}-\\d{2}-\\d{2}'), django.core.validators.MinLengthValidator(19), django.core.validators.MaxLengthValidator(19)]),
        ),
    ]
