# Generated by Django 5.0.5 on 2024-05-20 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0007_alter_sale_employee'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
