# Generated by Django 5.0.5 on 2024-05-21 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0009_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
