# Generated by Django 5.0.5 on 2024-05-22 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0011_remove_sale_employee_alter_sale_buyer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='date_of_birth',
            new_name='birthdate',
        ),
    ]
