# Generated by Django 5.1.1 on 2024-09-16 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0015_remove_cart_created_at_remove_cart_properties_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='properties',
            field=models.ManyToManyField(related_name='carts', through='agency.CartItem', to='agency.property'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agency.cart'),
        ),
    ]
