# Generated by Django 5.1.1 on 2024-09-19 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0018_alter_coupon_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='job',
            field=models.CharField(default='just chill', max_length=20),
            preserve_default=False,
        ),
    ]
