# Generated by Django 5.1.1 on 2024-09-20 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0019_employer_job'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Coupon',
        ),
    ]
