from django.urls import re_path
from . import views

urlpatterns = [
    re_path(r'^$', views.home, name='home'),
    re_path(r'^about/$', views.about, name='about'),
    re_path(r'^news/$', views.news, name='news'),
    re_path(r'^dictionary/$', views.dictionary, name='dictionary'),
    re_path(r'^contacts/$', views.contacts, name='contacts'),
    re_path(r'^privacy_policy/$', views.privacy_policy, name='privacy_policy'),
    re_path(r'^vacancies/$', views.vacancies, name='vacancies'),
    re_path(r'^reviews/$', views.reviews, name='reviews'),
    re_path(r'^news/(?P<article_id>\d+)/$',
            views.article_detail, name='article_detail'),
    re_path(r'^coupons/$', views.coupons, name='coupons'),
    re_path(r'^properties/(?P<property_id>\d+)/$',
            views.property_detail, name='property_detail'),
    re_path(r'^statistics/$', views.statistics, name='statistics'),
    re_path(r'^profile/$', views.profile, name='profile'),
    re_path(r'^properties/$', views.property_list, name='property_list'),
    re_path(r'^properties/add/$', views.property_create, name='property_create'),
    re_path(r'^properties/(?P<pk>\d+)/edit/$',
            views.property_update, name='property_update'),
    re_path(r'^properties/(?P<pk>\d+)/delete/$',
            views.property_delete, name='property_delete'),
    re_path(r'^contacts/manage/$', views.contact_list, name='contact_list'),
    re_path(r'^contacts/add/$', views.contact_create, name='contact_create'),
    re_path(r'^contacts/(?P<pk>\d+)/edit/$',
            views.contact_update, name='contact_update'),
    re_path(r'^contacts/(?P<pk>\d+)/delete/$',
            views.contact_delete, name='contact_delete'),
    re_path(r'^purchase/(?P<property_id>\d+)/$',
            views.purchase_property, name='purchase_property'),
    re_path(r'^profile/cart/', views.cart_view, name='cart'),
    re_path(r'^remove_from_cart/(?P<property_id>\d+)/$', views.remove_from_cart, name='remove_from_cart'),
    re_path(r'^add_to_cart/(?P<property_id>\d+)/$', views.add_to_cart, name='add_to_cart'),
    re_path(r'^update_quantity/(?P<property_id>\d+)/$', views.update_quantity, name='update_quantity'),
    re_path(r'^purchase_property/(?P<property_id>\d+)/$', views.purchase_property, name='purchase_property'),
    re_path(r'^apply_coupon/$', views.apply_coupon, name='apply_coupon'),
    re_path(r'^update_cart/$', views.cart_view, name='update_cart'),
    re_path(r'^reviews/add/', views.add_review, name='add_review'),
]
